Repository aditikilledar/burnout-proj3, pull requests merged in 2023-11, with the labels that each got.

#26 BMI calculation
  backend/base.py
  frontend/src/components/Profile.js
Labels: enhancement

#30 Randomizing featured exercises
  frontend/public/assets/img/featured/1.gif
  frontend/public/assets/img/featured/2.gif
  frontend/public/assets/img/featured/3.gif
  frontend/public/assets/img/featured/4.gif
  frontend/public/assets/img/featured/5.gif
  frontend/public/assets/img/featured/6.gif
  frontend/public/assets/img/featured/7.gif
  frontend/public/assets/img/october19.gif
  frontend/src/components/UserCaloriesPage.js
Labels: enhancement

#29 Feature google sign in
  backend/base.py
  frontend/package.json
  frontend/src/components/authentication/SignIn.js
  frontend/src/index.js
Labels: enhancement

#36 Target calories and BMI instant update & bug resolution with update button
  backend/base.py
  frontend/src/components/Profile.js
Labels: bug

#52 Contact us now has a Form for easy Emails. Fixes issue #48
  frontend/src/components/ContactUs.js
Labels: enhancement

#49 Adding toggle for unit change
  frontend/src/components/Profile.js
Labels: enhancement

#65 Dont allow repeated unit change
  frontend/src/components/Profile.js
Labels: bug

#75 Code cleanup
  frontend/src/components/App.js
  frontend/src/components/ContactUs.js
  frontend/src/components/Events.js
  frontend/src/components/Header.js
  frontend/src/components/Home.js
  frontend/src/components/Meals.js
  frontend/src/components/Profile.js
  frontend/src/components/Router.js
  frontend/src/components/UserCaloriesPage.js
  frontend/src/components/faq.js
Labels: bug

#84 Fix for build script workflow
  .github/workflows/style_checker.yml
  backend/requirements.txt
  frontend/src/components/Events.js
  frontend/src/components/Meals.js
  frontend/src/components/Profile.js
  frontend/src/components/UserCaloriesPage.js
  frontend/src/components/authentication/SignIn.js
Labels: bug

#85 Updated dev documentation and readme
  Developer_README.md
  README.md
  frontend/src/components/Footer.js
  frontend/src/components/UserCaloriesPage.js
Labels: documentation

#87 Updating deps in dev docs
  Developer_README.md
  README.md
Labels: documentation

#88 Updating citations
  CITATIONS.md
  Developer_README.md
  README.md
Labels: documentation

#92 Adding pydocs
  backend/docs/index.html
  docs/base.html
  docs/index.html
  docs/search.js
  docs/test_api.html
Labels: documentation

#93 Adding new doc link
  Developer_README.md
  README.md
Labels: documentation
